### ISSUE TITLE
`ThreeQubitSquash` should not be part of default optimization pass on IBMQ devices

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#101]
It breaks connectivity constraints.

**Comment by yao-cqc** [comment]
I've just looked through the code, it seems that all `FullPeepholeOptimise` passes are ran before routing for all architectures with limited architectures.

**Comment by cqc-alec** [comment]
> I've just looked through the code, it seems that all `FullPeepholeOptimise` passes are ran before routing for all architectures with limited architectures.

Phew, I guess we can close this then!
