### ISSUE TITLE
IBMQBackend.available_devices type error

### ISSUE THREAD

**Issue by vanyae-cqc** [CQCL/pytket-qiskit#141]
For `IBMQBackend` I believe the type for `BackendInfo.device_name` is incorrect on the `BackendInfo`s returned from `available_devices`. It should return a `str` but instead returns a method.

Minimal example:

```python
from pytket.extensions.qiskit import IBMQBackend

from qiskit.providers.ibmq import IBMQFactory

account_provider = IBMQFactory().enable_account(
    token=token,
    hub="ibm-q",
    group="open",
    project="main",
)

backend_infos = IBMQBackend.available_devices(provider=account_provider)

print(backend_infos[0].device_name)
```

Outputs:

```
<bound method BackendV1.name of <IBMQSimulator('ibmq_qasm_simulator') from IBMQ(hub='ibm-q', group='open', project='main')>>
```

**Comment by CalMacCQ** [comment]
Hi,

My understanding was that `IBMQFactory` has been deprecated. I could be wrong about this.

If instead I use [IBMProvider](https://qiskit.org/ecosystem/ibm-provider/stubs/qiskit_ibm_provider.IBMProvider.html#ibmprovider) I get the correct type for the `device_name`

```python
from qiskit_ibm_provider import IBMProvider
from pytket.extensions.qiskit import IBMQBackend

instance='ibm-q/open/main'
ibm_provider = IBMProvider(instance=instance)

backend_infos = IBMQBackend.available_devices(provider=ibm_provider)

print(type(backend_infos[0].device_name))
```

I get `<class 'str'>`

Does this work for you?

**Comment by vanyae-cqc** [comment]
Ah yes, I was indeed passing the deprecated `AccountProvider`, can confirm this works now. Thanks for the speedy response!
