### ISSUE TITLE
RuntimeJobFailureError with ECR instruction on IBMQBackends (Eagle Processors)

### ISSUE THREAD

**Issue by spendierk** [CQCL/pytket-qiskit#164]
Encountered a `RuntimeJobFailureError` related to the ECR instruction on various Eagle processor `IBMQBackends` using `pytket-qiskit` versions 0.41.0, 0.43.0, and 0.42.0. The error does not manifest with `IBMQEmulatorBackend`.

Example error message for `backend = IBMQBackend("ibm_nazca")`

```
RuntimeJobFailureError: 'Unable to retrieve job result. INSTRUCTION NOT IN BASIS GATES: INSTRUCTION: ECR, QUBITS: [2, 1], PARAMS: []
```

**Comment by CalMacCQ** [comment]
I looked into this a bit yesterday. I'm not whether its an issue with `pytket-qiskit` or on the IBM side.

```python
from pytket import Circuit
from pytket.extensions.qiskit import IBMQEmulatorBackend
backend = IBMQEmulatorBackend("ibm_nazca")
circ = Circuit(3, 3)
circ.X(1).CZ(0, 1).CX(1, 2).measure_all()
circ = backend.get_compiled_circuit(circ)
handle = backend.process_circuit(circ, n_shots=1000)
# assert backend.persistent_handles
print(str(handle))
counts = backend.get_result(handle).get_counts()
print(counts)
```

This works fine on the `IBMQEmulatorBackend` as was pointed out above. However if I use `IBMQBackend` I get a `RuntimeJobFailureError` as above which is puzzling.

Nasca uses the new IBM gateset of {X, SX, Rz, ECR} which I added support for in pytket-qiskit in version [0.40.0](https://cqcl.github.io/pytket-qiskit/api/changelog.html#june-2023).

Whats weird is that the circuit seems to be valid in the sense that it satisfies the gateset and connectivtity constraints but fails upon execution with the `RuntimeJobFailureError`.

For the circuit above I can check validity with `IBMQBackend.valid_circuit` and it seems to be fine. Compilation to the {X, SX, Rz, ECR} gateset is tested on CI [here](https://github.com/CQCL/pytket-qiskit/blob/develop/tests/backend_test.py#L1209) but we don't run any jobs.

I also get a similar issue with the Cusco device which also uses {X, SX, Rz, ECR}.

**Comment by CalMacCQ** [comment]
Works for me now too :) Looks like you were right and it was a temporary issue on the IBM side.

Glad to hear it isn't a bug in our IBM backend code

**Comment by spendierk** [comment]
Works for me now too, thank you!

**Comment by spendierk** [comment]
Works for me now too, thank you!
