### ISSUE TITLE
Dependency specifier for `pytket` should be tighter

### ISSUE THREAD

**Issue by burgholzer** [CQCL/pytket-qiskit#182]
Hey 👋🏼 

Due to the way the version range for the `pytket` dependency is specified (`pytket~=1.x`), an install of the `pytket-qiskit` extension will always pull in the latest minor version of `pytket` instead of the latest version compatible with the given minor version.

This has surfaced in one of our projects that uses the `pytket-qiskit` extension: https://github.com/cda-tum/mqt-predictor/discussions/135.
From there:
> The above command install pytket-qiskit 0.39.0.
That package declares a dependency on pytket~=0.15.
Due to the way dependencies work in Python, this installs pytket-1.20.1, when in reality the TKET developers most likely intended to write pytket~=0.15.0, which would have led to pytket-1.15.0 being installed.

I would assume that you want to express the `pytket` dependency as
```
pytket~=1.x.0
```
for any given minor version `x` to ensure proper compatibility.

**Comment by burgholzer** [comment]
Yeah. That's exactly what brought me here.
I can confirm that the newest versions work just fine.
Thanks for clarifying and feel free to close this "issue" (Should have opened it as a discussion 🙃)

**Comment by cqc-alec** [comment]
OK good! Will close this issue then.
