### ISSUE TITLE
Gate has an invalid number of parameters

### ISSUE THREAD

**Issue by sirgeorgesawcon** [CQCL/pytket-qiskit#200]
# The Error
I have a circuit made using qiskit, I'm converting it to `tket` using 

```python
from pytket.extensions.qiskit import qiskit_to_tk
c = qiskit_to_tk(qc)
```

but I'm getting the following error:

```
RuntimeError: Gate has an invalid number of parameters
```

#  How to Reproduce the Error?

The circuit is a bit complex, it requires some inbuilt Qiskit functionalities and ansatsz, here is the code:

```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import RealAmplitudes
from qiskit_finance.circuit.library import NormalDistribution

qc = QuantumCircuit(15)
mu = 5
sigma = 2
# loading the demand distribution
demand = NormalDistribution(num_qubits=3,mu=mu,sigma=sigma,  bounds=[0,7])
params = [np.pi/2]*18   
supply1 = RealAmplitudes(3, reps=2)
supply2 = RealAmplitudes(3, reps=2)
    # taking the parameters from the list
list1 = params[:9]
list2 = params[9:]

    
supply1 = supply1.assign_parameters(list1)
supply2 = supply2.assign_parameters(list2)


qc.compose(demand,qubits=[8,9,10], inplace=True)
qc.compose(supply1, qubits = [0,1,2], inplace=True)
qc.compose(supply2, qubits = [3,4,5], inplace=True)
qc.draw('mpl')
```

Here is how the circuit looks like :

![wqe](https://github.com/CQCL/pytket-extensions/assets/63145298/24e52d6f-93b7-4445-922a-c858f92d6682)

then using `pytket`

```python
from pytket.extensions.qiskit import qiskit_to_tk
c = qiskit_to_tk(qc)
```
I'm getting the following error:

```
RuntimeError: Gate has an invalid number of parameters
```

**Comment by CalMacCQ** [comment]
Hi,

Thanks for making an issue for this. Here is a smaller snippet that reproduces the `RuntimeError`.

```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import RealAmplitudes

qc = QuantumCircuit(3)

params = [np.pi/2]*9
supply1 = RealAmplitudes(3, reps=2)

list1 = params[:9]
   
supply1 = supply1.assign_parameters(list1)
qc.compose(supply1, qubits = [0, 1, 2], inplace=True)

tkc = qiskit_to_tk(qc)
```

The `qiskit_to_tk` function appears to be trying to convert the `RealAmplitudes` instruction to a `CustomGate` and failing. 

Relevant source line -> [here](https://github.com/CQCL/pytket-qiskit/blob/develop/pytket/extensions/qiskit/qiskit_convert.py#L496)

I'll look into this some more.

**Comment by CalMacCQ** [comment]
In the next release, the `RealAmplitudes` instruction should be handled as a `CircBox`

If there are any further problems please make a new issue or reopen this one.

Thanks again

**Comment by CalMacCQ** [comment]
As a temporary workaround you could decompose the quantum circuit with `QuantumCircuit.decompose()` before using `qiskit_to_tk`.
