### ISSUE TITLE
Support density matrix simulation

### ISSUE THREAD

**Issue by yao-cqc** [CQCL/pytket-qiskit#231]

**Comment by cqc-melf** [comment]
I think we can close this as wont do, as the remote MPS will be retired? @cqc-alec

**Comment by cqc-alec** [comment]
> I think we can close this as wont do, as the remote MPS will be retired? @cqc-alec

Unless we want a local DM simulator; does qiskit offer one of these?

**Comment by cqc-melf** [comment]
It would be possible to do that locally: https://qiskit.github.io/qiskit-aer/stubs/qiskit_aer.QasmSimulator.html
