### ISSUE TITLE
Wrong qubit number reported by simulator

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#272]
See for example https://github.com/CQCL/pytket-qiskit/actions/runs/7987543748/job/21810227707 .

Three of the tests are failing, with errors like this:

```
qiskit_ibm_runtime.exceptions.RuntimeJobFailureError: 'Unable to retrieve job result. Number of qubits (127) in circuit-241006 is greater than maximum (31) in the coupling_map -- Verify the input circuits and the traspilation options. -- https://ibm.biz/error_codes#1516'
```

**Comment by cqc-melf** [comment]
See https://github.com/Qiskit/qiskit/issues/11939

**Comment by cqc-melf** [comment]
It looks like this is an issue in qiskit, I have submitted a bug report.

**Comment by cqc-melf** [comment]
simulator remove, solved
