### ISSUE TITLE
cx gate not supported by stabilizer backend with qiskit-ibm-runtime >= 0.20

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#278]
Failing on CI with this error:

```
FAILED backend_test.py::test_cloud_stabiliser - qiskit.transpiler.exceptions.TranspilerError: "The number of qubits for Instruction(name='cx', num_qubits=2, num_clbits=0, params=[]) does not match the number of qubits in the properties dictionary: (0,)"
```

See e.g. https://github.com/CQCL/pytket-qiskit/actions/runs/8140202781/job/22245616314?pr=268

**Comment by cqc-alec** [comment]
Note, this is a result of upgrading qiskit-ibm-runtime to 0.20.0; the problem is not present on `develop`.

**Comment by cqc-melf** [comment]
Reported to qiskit: see https://github.com/Qiskit/qiskit/issues/11957

**Comment by cqc-melf** [comment]
See https://github.com/Qiskit/qiskit-ibm-runtime/issues/1475

**Comment by cqc-melf** [comment]
This now shows up on develop

**Comment by cqc-melf** [comment]
simulator removed, problem solved
