### ISSUE TITLE
`qiskit_algorithms` dependency upgrade to `v0.30.0`

### ISSUE THREAD

**Issue by nquetschlich** [CQCL/pytket-qiskit#293]
Hi there,

currently, the `qiskit_algorithms` dependency is `~=0.21.0`. Unfortunately, that version has some issues with `Qiskit v1.0.0` (see https://github.com/qiskit-community/qiskit-algorithms/issues/157) which have been fixed in `qiskit_algorithms v0.30.0`. Would it be possible to adjust the requirement in `pytket_qiskit` accordingly? 

That would be highly appreciated :)

**Comment by cqc-melf** [comment]
Assuming you are talking about 0.3.0 ?
We have just done that in https://github.com/CQCL/pytket-qiskit/pull/294

**Comment by nquetschlich** [comment]
Yes, exactly. Thanks a lot!

**Comment by cqc-melf** [comment]
The update as been released just now on pytket-qiksit 0.50.0 see https://tket.quantinuum.com/extensions/pytket-qiskit/changelog.html @nquetschlich
