### ISSUE TITLE
Qiskit Conversion ignores implict permutations

### ISSUE THREAD

**Issue by christian512** [CQCL/pytket-qiskit#411]
If a `Circuit` object contains `implicit_permutations` the conversion using `tk_to_qiskit` ignores these permutations leading to an inequivalent circuit (see example below).

I would suggest to (at least) raise a warning that the conversion function is called on a circuit containing implicit permutations.

```Python
from pytket import Circuit
from pytket.extensions.qiskit import qiskit_to_tk, tk_to_qiskit
from pytket.utils import compare_statevectors

circuit_dict = {'bits': [],
     'commands': [
         {'args': [['q', [0]]], 'op': {'type': 'X'}},
         {'args': [['q', [1]]], 'op': {'type': 'Y'}},
         {'args': [['q', [2]]], 'op': {'type': 'Z'}},],
         'implicit_permutation': [[['q', [0]], ['q', [0]]],
                                  [['q', [1]], ['q', [2]]],
                                  [['q', [2]], ['q', [1]]]],
         'phase': '0.0',
         'qubits': [['q', [0]], ['q', [1]], ['q', [2]]]
    }

circ = Circuit.from_dict(circuit_dict)

# Pass the circuit through qiskit conversion
qiskit_circ = tk_to_qiskit(circ)
print(qiskit_circ)
circ_after_conversion = qiskit_to_tk(qiskit_circ)

# This statevector comparison fails
assert compare_statevectors(circ_after_conversion.get_statevector(), circ.get_statevector())
```

**Comment by CalMacCQ** [comment]
Thanks for raising this issue. This is definetly something we should address.

**Comment by CalMacCQ** [comment]
Maybe just emitting a warning saying that the circuit contains implcit permutations is the best way to tackle this. Any thoughts @cqc-alec ?

**Comment by cqc-alec** [comment]
Note that there is also a `replace_implicit_swaps` argument to `tk_to_qiskit` that implements the implicit permutation using swaps. But yes, I think emitting a warning if this is omitted (or `False`) and the circuit has a non-trivial implicit permutation is a good idea.

**Comment by christian512** [comment]
What about an option to deactivate the warnings?

The backends could use `tk_to_qiskit(..., warn=False)` where `warn` is an optional parameter that defaults to `True`.

**Comment by CalMacCQ** [comment]
> What about an option to deactivate the warnings?
> 
> The backends could use `tk_to_qiskit(..., warn=False)` where `warn` is an optional parameter that defaults to `True`.

I did consider this as an option. Could be worth doing actually.

I think it is still useful to give a warning for implicit permutations. I just want to avoid giving users unhelpful warnings when using the backends that they cannot address

**Comment by CalMacCQ** [comment]
I'll add the warning back in with the flag. Should be quick.
