### ISSUE TITLE
Test failure: `test_cnry_conversion`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#429]
```
FAILED qiskit_convert_test.py::test_cnry_conversion - AttributeError: 'Instruction' object has no attribute 'num_ctrl_qubits'
```

**Comment by CalMacCQ** [comment]
Hmm seems its a property of `ControlledGate` which inherits from `Instruction` 

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.ControlledGate#controlledgate

**Comment by cqc-alec** [comment]
This does seem like a bug in qiskit. The following code:

```python
from qiskit import QuantumCircuit, QuantumRegister, transpile
from qiskit.circuit.library import MCMT, RYGate
from qiskit_aer import Aer


qr = QuantumRegister(2, "q")
qcirc = QuantumCircuit(qr)
ry_gate = RYGate(0.1)
cry_gate = MCMT(gate=ry_gate, num_ctrl_qubits=1, num_target_qubits=1)
qcirc.append(cry_gate, [qr[0], qr[1]])

backend = Aer.get_backend("aer_simulator_unitary")

transpile(qcirc, backend)
```

succeeds with qiskit 1.2.4, but fails with qiskit 1.3.1.

**Comment by CalMacCQ** [comment]
MCMT seems to be deprecated since 1.3 but would not have expected it to be removed.

**Comment by cqc-alec** [comment]
> MCMT seems to be deprecated since 1.3 but would not have expected it to be removed.

Ah good spot. I think we can just change to `MCMTGate` and it works.

**Comment by cqc-alec** [comment]
`MCMTGate` was only introduced in 1.3 so we have to upgrade to that in order to use it.
