### ISSUE TITLE
[tests] remove deprecation warnings from qiskit backend tests

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#68]
```
tests/qiskit_backend_test.py::test_grover
  [...]/tests/qiskit_backend_test.py:164: PendingDeprecationWarning: The quantum_instance argument has been superseded by the sampler argument. This argument will be deprecated in a future release and subsequently removed after that.
    grover = Grover(quantum_instance=qinstance)

```

**Comment by isobelhooper** [comment]
Our project that uses pytket-qiskit for tests is also running into a lot of the following deprecation warnings:

```
DeprecationWarning: The ``qiskit.opflow`` module is deprecated as of qiskit-terra 0.24.0. It will be removed no earlier than 3 months after the release date. For code migration guidelines, visit https://qisk.it/opflow_migration.
    from qiskit.opflow import PauliSumOp
```

which sound like they may be the same sort of issue.

**Comment by isobelhooper** [comment]
It looks like we may be getting these deprecation warnings emitted by the new API, `qiskit.primitives`, based on this issue in qiskit-terra: https://github.com/Qiskit/qiskit-terra/issues/10245

A fix has gone in to suppress those warnings when things are imported via `qiskit.primitives`, but it hasn't made it into a qiskit-terra release yet.

**Comment by cqc-alec** [comment]
Done in #331 .
