### ISSUE TITLE
TypeError: 'IBMQEmulatorBackend' object is not subscriptable

### ISSUE THREAD

**Issue by NickGut0711** [CQCL/pytket-qiskit#69]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[21], line 4
      1 from pytket.placement import NoiseAwarePlacement, GraphPlacement
      2 from pytket.extensions.qiskit.qiskit_convert import get_avg_characterisation
----> 4 backend_avg = get_avg_characterisation(backend)
      7 avg_char = [node_errors, edge_errors, readout_errors]
      9 noise_placer = NoiseAwarePlacement(backend.backend_info.architecture, **avg_char)

File /opt/.qbraid/environments/qbraid_000000/pyenv/lib/python3.9/site-packages/pytket/extensions/qiskit/qiskit_convert.py:791, in get_avg_characterisation(characterisation)
    788 map_values_t = Callable[[Callable[[V1], V2], Dict[K, V1]], Dict[K, V2]]
    789 map_values: map_values_t = lambda f, d: {k: f(v) for k, v in d.items()}
--> 791 node_errors = cast(Dict[Node, Dict[OpType, float]], characterisation["NodeErrors"])
    792 link_errors = cast(
    793     Dict[Tuple[Node, Node], Dict[OpType, float]], characterisation["EdgeErrors"]
    794 )
    795 readout_errors = cast(
    796     Dict[Node, List[List[float]]], characterisation["ReadoutErrors"]
    797 )

TypeError: 'IBMQEmulatorBackend' object is not subscriptable

**Comment by NickGut0711** [comment]
get_avg_characterisation returns multiple variables

**Comment by CalMacCQ** [comment]
Thanks Nick for raising this issue! Seems like it could be a bug.
