### ISSUE TITLE
``AerStateBackend`` doesn't support ``Measurement`` and ``Reset``

### ISSUE THREAD

**Issue by yao-cqc** [CQCL/pytket-qiskit#99]
Tested with 0.37.1
```
from pytket.extensions.qiskit import AerStateBackend
from pytket.circuit import Circuit,OpType
b = AerStateBackend()
c = Circuit(1,1).H(0).Measure(0,0).add_gate(OpType.Reset, [0]).H(0)
res = b.run_circuit(c)
```
raises ``CircuitNotValidError``. 

I've added ``Measurement `` and ``Reset`` to the gateset and tested locally, the backend works fine.

The capacity of the ``AerUnitaryBackend`` should also be checked.

**Comment by CalMacCQ** [comment]
Should `Circuit.get_statevector()` support `Reset` as well?
